algoritmo "Exercicio 1"
// Função :
// Autor :
// Data : 16/10/2023
// Seção de Declarações 
var
nome: caractere
anonasc, anoatual, idade: inteiro

inicio
escreva ("qual é o seu nome")
leia (nome)
escreva ("qual ano você nasceu: ")
leia (anonasc)
escreva ("qual ano atual: ")
leia (anoatual)
idade <- anoatual - anonasc
escreva ("seu nome é:", nome)
escreva ("sua idade é:", idade)


fimalgoritmo
